//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Education.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public int ID { get; set; }
        public string HoTen_GV { get; set; }
        public string NgaySinh { get; set; }
        public string Anh { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoGioGiang { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
    }
}
