//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Education.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GopY
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string ChuDe { get; set; }
        public string SDT { get; set; }
        public string NoiDung { get; set; }
        public string NgayNhan { get; set; }
    }
}
