//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Education.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocVien_KhoaHoc
    {
        public int IDKhoaHoc { get; set; }
        public int IDHocVien { get; set; }
        public string NgayDangKy { get; set; }
        public Nullable<int> ChuyenCan { get; set; }
        public Nullable<float> DiemDanhGia { get; set; }
        public Nullable<bool> ThanhToan { get; set; }
    }
}
